[project]
name = "teachart"
version = "1.0.0-a1"
description = "Qt based gui app to create lesson plans for teachers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "PyQt6>=6.6.10",
]

[project.scripts]
teachart = "main:main"

[dependency-groups]
build = ["ninja>=1.13.0", "pyinstaller>=6.0.0"] # Only includes necessary libraries to run app
dev = [ # Includes also libraries used for testing or formatting
    "PyQt6>=6.6.10",
    "PySide6>=6.6.0", # Only needed for parsing .qrc-files
    "pytest>=9.1.1",
    "ruff>=0.16.0",
    "ninja>=1.13.0" # For building commands
]
dist = ["pyinstaller>=6.0.0", "PySide6>=6.6.0",] # Tools needed to create a executable one file distribution

[tool.setuptools]
packages = ["tcha", "ui", "styling", "nativeelements", "styling.resources"]
py-modules = ["main"]
package-dir = {"" = "source"}

[tool.pytest.ini_options]
pythonpath = ["source"]
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py312"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
