[project]
name = "teachart"
version = "1.0.0-a1"
description = "Qt based gui app to create lesson plans for teachers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller",
    "PyQt6>=6.6.10",
]

[project.scripts]
teachart = "main:main"

[dependency-groups]
dev = [
    "PySide6>=6.6.0",
    "pytest>=9.1.1",
    "ruff>=0.16.0",
    "ninja>=1.13.0"
]
build = ["pyinstaller>=6.0.0"]

[tool.setuptools]
packages = ["tcha", "ui", "styling", "nativeelements"]
py-modules = ["main"]
package-dir = {"" = "source"}

[tool.pytest.ini_options]
pythonpath = ["source"]
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py312"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
