[project]
name = "teachart"
version = "1.0.0-a1"
description = "Qt based gui app to create lesson plans for teachers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "PyQt6",
    "pytest>=9.1.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = "source"
resources = "resources"
dev = "python source/main.py"
debug = "python  source/main.py debug"
clean = "python source/main.py clean"