"""Default base values."""

"""Coloring tuple: (transparency, darkening factor, lightening factor)"""

THEME_COLOR_VALUES = {
    "dark": {
        "background": {
            "base": "#202124",
            "list": (),
            "panel": (0.0, 0.3, 0.0),
            "popup": (0.0, 0.0, 0.3),
            "table": (0.0, 0.5, 0.0),
            "textarea": (0.0, 0.13, 0.0),
            "title": (0.0, 0.3, 0.0),
        },
        "border": {
            "base": "#3f4042",
            "input": (0, 0, 0),
        },
        "foreground": {
            "base": "#e4e7eb",
            "defaultButton.disabledBackground": (0.2, 0.0, 0.0),
            "disabled": (0.4, 0.0, 0.0),
            "disabledSelectionBackground": (0.2, 0.0, 0.0),
            "icon": (0.0, 0.01, 0.0),
            "icon.unfocused": (0.6, 0.0, 0.0),
            "input.placeholder": (0.6, 0.0, 0.0),
            "progressBar.disabledBackground": (0.2, 0.0, 0.0),
            "slider.disabledBackground": (0.2, 0.0, 0.0),
            "sliderTrack.inactiveBackground": (0.1, 0.0, 0.0),
        },
        "input.background": "#3f4042",
        "inputButton.hoverBackground": "#ffffff25",
        "linkVisited": "#c58af8",
        "list.alternateBackground": "#ffffff0c",
        "list.hoverBackground": "#ffffff13",
        "menubar.selectionBackground": "#ffffff25",
        "popupItem.checkbox.background": "#ffffff19",
        "popupItem.selectionBackground": "#ffffff22",
        "primary": {
            "base": "#8ab4f7",
            "button.activeBackground": (0.23, 0.14, 0.0),
            "button.hoverBackground": (0.11, 0.1, 0.0),
            "defaultButton.activeBackground": (0.0, 0.12, 0.0),
            "defaultButton.hoverBackground": (0.0, 0.06, 0.0),
            "list.inactiveSelectionBackground": (0.15, 0.0, 0.2),
            "list.selectionBackground": (0.4, 0.2, 0.0),
            "progressBar.background": (0.0, 0.1, 0.0),
            "selection.background": (0.4, 0.2, 0.1),
            "sliderHandle.activeBackground": (0.0, 0.09, 0.0),
            "table.inactiveSelectionBackground": (0.18, 0.0, 0.2),
            "table.selectionBackground": (0.55, 0.2, 0.0),
            "textarea.selectionBackground": (0.4, 0.2, 0.1),
        },
        "scrollbar.background": "#ffffff10",
        "scrollbarSlider.activeBackground": "#ffffff60",
        "scrollbarSlider.background": "#ffffff30",
        "scrollbarSlider.disabledBackground": "#ffffff15",
        "scrollbarSlider.hoverBackground": "#ffffff45",
        "statusBar.background": "#2a2b2e",
        "statusBarItem.activeBackground": "#ffffff34",
        "statusBarItem.hoverBackground": "#ffffff22",
        "tab.activeBackground": "#ffffff00",
        "tab.hoverBackground": "#ffffff18",
        "tabCloseButton.hoverBackground": "#ffffff25",
        "table.alternateBackground": "#ffffff15",
        "tableSectionHeader.background": "#3f4042",
        "textarea.inactiveSelectionBackground": "#ffffff20",
        "toolbar.activeBackground": "#ffffff34",
        "toolbar.background": "#333333",
        "toolbar.hoverBackground": "#ffffff22",
        "tree.inactiveIndentGuidesStroke": "#ffffff35",
        "tree.indentGuidesStroke": "#ffffff60",
        "treeSectionHeader.background": "#3f4042",
    },
    "light": {
        "background": {
            "base": "#f8f9fa",
            "list": (),
            "panel": (0.0, 0.0, 0.5),
            "popup": (0.0, 0.0, 0.2),
            "table": (0.0, 0.0, 0.5),
            "textarea": (0.0, 0.0, 0.25),
            "title": (0.0, 0.04, 0.0),
        },
        "border": {
            "base": "#dadce0",
            "input": (),
        },
        "foreground": {
            "base": "#4d5157",
            "defaultButton.disabledBackground": (0.25, 0.0, 0.0),
            "disabled": (0.4, 0.0, 0.0),
            "disabledSelectionBackground": (0.25, 0.0, 0.0),
            "icon": (0.0, 0.05, 0.0),
            "icon.unfocused": (0.6, 0.0, 0.0),
            "input.placeholder": (0.6, 0.0, 0.0),
            "progressBar.disabledBackground": (0.25, 0.0, 0.0),
            "slider.disabledBackground": (0.25, 0.0, 0.0),
            "sliderTrack.inactiveBackground": (0.2, 0.0, 0.0),
        },
        "input.background": "#f8f9fa",
        "inputButton.hoverBackground": "#00000018",
        "linkVisited": "#660098",
        "list.alternateBackground": "#00000009",
        "list.hoverBackground": "#00000013",
        "menubar.selectionBackground": "#00000020",
        "popupItem.checkbox.background": "#00000019",
        "popupItem.selectionBackground": "#00000022",
        "primary": {
            "base": "#1a73e8",
            "button.activeBackground": (0.24, 0.03, 0.0),
            "button.hoverBackground": (0.1, 0.03, 0.0),
            "defaultButton.activeBackground": (0.0, 0.0, 0.3),
            "defaultButton.hoverBackground": (0.0, 0.0, 0.1),
            "list.inactiveSelectionBackground": (0.09, 0.43, 0.0),
            "list.selectionBackground": (0.35, 0.0, 0.2),
            "progressBar.background": (0.0, 0.0, 0.2),
            "selection.background": (0.5, 0.0, 0.3),
            "sliderHandle.activeBackground": (0.0, 0.0, 0.2),
            "table.inactiveSelectionBackground": (0.09, 0.43, 0.0),
            "table.selectionBackground": (0.5, 0.0, 0.1),
            "textarea.selectionBackground": (0.5, 0.0, 0.3),
        },
        "scrollbar.background": "#00000010",
        "scrollbarSlider.activeBackground": "#00000060",
        "scrollbarSlider.background": "#00000040",
        "scrollbarSlider.disabledBackground": "#00000015",
        "scrollbarSlider.hoverBackground": "#00000050",
        "statusBar.background": "#dfe1e5",
        "statusBarItem.activeBackground": "#00000024",
        "statusBarItem.hoverBackground": "#00000015",
        "tab.activeBackground": "#00000000",
        "tab.hoverBackground": "#00000015",
        "tabCloseButton.hoverBackground": "#00000020",
        "table.alternateBackground": "#00000012",
        "tableSectionHeader.background": "#dadce0",
        "textarea.inactiveSelectionBackground": "#00000015",
        "toolbar.activeBackground": "#00000024",
        "toolbar.background": "#ebebeb",
        "toolbar.hoverBackground": "#00000015",
        "tree.inactiveIndentGuidesStroke": "#00000030",
        "tree.indentGuidesStroke": "#00000050",
        "treeSectionHeader.background": "#dadce0",
    },
}

ACCENT_COLORS = {
    "dark": {
        "blue": "#8ab4f7",
        "graphite": "#898a8f",
        "green": "#4caf50",
        "orange": "#ff9800",
        "pink": "#c7457f",
        "purple": "#af52bf",
        "red": "#f6685e",
        "yellow": "#ffeb3b",
    },
    "light": {
        "blue": "#1a73e8",
        "graphite": "#898a8f",
        "green": "#4caf50",
        "orange": "#ff9800",
        "pink": "#c7457f",
        "purple": "#9c27b0",
        "red": "#f44336",
        "yellow": "#f4c65f",
    },
}
