# Form implementation generated from reading ui file 'D:\Coding\Teachart\designer\ui_add_edit_schedule.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditScheduleDialog(object):
    def setupUi(self, EditScheduleDialog):
        EditScheduleDialog.setObjectName("EditScheduleDialog")
        EditScheduleDialog.resize(288, 107)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(EditScheduleDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=EditScheduleDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=EditScheduleDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=EditScheduleDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox = QtWidgets.QComboBox(parent=EditScheduleDialog)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=EditScheduleDialog)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout_3.addWidget(self.dateTimeEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=EditScheduleDialog)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=EditScheduleDialog)
        self.pushButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=EditScheduleDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(EditScheduleDialog)
        self.buttonBox.accepted.connect(EditScheduleDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(EditScheduleDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditScheduleDialog)

    def retranslateUi(self, EditScheduleDialog):
        _translate = QtCore.QCoreApplication.translate
        EditScheduleDialog.setWindowTitle(_translate("EditScheduleDialog", "Dialog"))
        self.label.setText(_translate("EditScheduleDialog", "Course"))
        self.label_2.setText(_translate("EditScheduleDialog", "Date / Time"))
        self.label_3.setText(_translate("EditScheduleDialog", "File"))
        self.pushButton.setText(_translate("EditScheduleDialog", "..."))
