# Form implementation generated from reading ui file 'D:\Coding\Teachart\designer\ui_about.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(572, 314)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AboutDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_logo = QtWidgets.QLabel(parent=AboutDialog)
        self.lb_logo.setMinimumSize(QtCore.QSize(185, 0))
        self.lb_logo.setMaximumSize(QtCore.QSize(180, 180))
        self.lb_logo.setText("")
        self.lb_logo.setPixmap(QtGui.QPixmap(":/logo/logo_main"))
        self.lb_logo.setScaledContents(True)
        self.lb_logo.setObjectName("lb_logo")
        self.horizontalLayout.addWidget(self.lb_logo)
        self.sa_description = QtWidgets.QScrollArea(parent=AboutDialog)
        self.sa_description.setWidgetResizable(True)
        self.sa_description.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.sa_description.setObjectName("sa_description")
        self.sawidget = QtWidgets.QWidget()
        self.sawidget.setGeometry(QtCore.QRect(0, 0, 369, 300))
        self.sawidget.setMinimumSize(QtCore.QSize(365, 300))
        self.sawidget.setObjectName("sawidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sawidget)
        self.verticalLayout.setContentsMargins(-1, 2, -1, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_description = QtWidgets.QLabel(parent=self.sawidget)
        self.lb_description.setMinimumSize(QtCore.QSize(360, 300))
        self.lb_description.setOpenExternalLinks(True)
        self.lb_description.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.lb_description.setObjectName("lb_description")
        self.verticalLayout.addWidget(self.lb_description)
        self.sa_description.setWidget(self.sawidget)
        self.horizontalLayout.addWidget(self.sa_description)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About Teachart"))
        self.lb_description.setText(_translate("AboutDialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Teachart</span></p><p><br/><span style=\" font-size:10pt;\">Teachart is a tool for teachers to create lesson plans in a table structure. <br/>Teachart is a free software and currently still in development.</span></p><p><span style=\" font-size:10pt;\">Version [Version]<br/>Python [Python] <br/>Qt [Qt]</span></p><p><a href=\"https://github.com/DeatorFM/Educhart\"><span style=\" font-size:10pt; text-decoration: underline; color:#0000ff;\">Git Hub</span></a></p><p><span style=\" font-size:10pt;\">Written and translated in German by Florian Münstermann. </span></p><p><span style=\" font-size:10pt;\">UI Design adapted from PyQtDarkTheme by 5yutan5:<br/></span><a href=\"https://github.com/5yutan5/PyQtDarkTheme\"><span style=\" font-size:10pt; text-decoration: underline; color:#0000ff;\">PyQtDarkTheme on Git Hub</span></a></p><p><span style=\" font-size:10pt;\">Logo is a placeholder published by OpenClipart on public domain.</span></p></body></html>"))
