# Form implementation generated from reading ui file 'D:\Coding\Teachart\designer\ui_add_course.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddCourseDialog(object):
    def setupUi(self, AddCourseDialog):
        AddCourseDialog.setObjectName("AddCourseDialog")
        AddCourseDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        AddCourseDialog.resize(270, 120)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddCourseDialog.sizePolicy().hasHeightForWidth())
        AddCourseDialog.setSizePolicy(sizePolicy)
        AddCourseDialog.setMinimumSize(QtCore.QSize(270, 120))
        AddCourseDialog.setMaximumSize(QtCore.QSize(270, 120))
        self.vl1 = QtWidgets.QVBoxLayout(AddCourseDialog)
        self.vl1.setObjectName("vl1")
        self.hl1 = QtWidgets.QHBoxLayout()
        self.hl1.setObjectName("hl1")
        self.vl2 = QtWidgets.QVBoxLayout()
        self.vl2.setContentsMargins(-1, 2, -1, -1)
        self.vl2.setObjectName("vl2")
        self.lb_cname = QtWidgets.QLabel(parent=AddCourseDialog)
        self.lb_cname.setObjectName("lb_cname")
        self.vl2.addWidget(self.lb_cname)
        self.lb_cduration_2 = QtWidgets.QLabel(parent=AddCourseDialog)
        self.lb_cduration_2.setObjectName("lb_cduration_2")
        self.vl2.addWidget(self.lb_cduration_2)
        self.hl1.addLayout(self.vl2)
        self.vl3 = QtWidgets.QVBoxLayout()
        self.vl3.setObjectName("vl3")
        self.le_cname = QtWidgets.QLineEdit(parent=AddCourseDialog)
        self.le_cname.setMinimumSize(QtCore.QSize(0, 30))
        self.le_cname.setObjectName("le_cname")
        self.vl3.addWidget(self.le_cname)
        self.hl2 = QtWidgets.QHBoxLayout()
        self.hl2.setObjectName("hl2")
        self.sb_duration = QtWidgets.QSpinBox(parent=AddCourseDialog)
        self.sb_duration.setMinimumSize(QtCore.QSize(0, 30))
        self.sb_duration.setMaximum(1000)
        self.sb_duration.setObjectName("sb_duration")
        self.hl2.addWidget(self.sb_duration)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hl2.addItem(spacerItem)
        self.vl3.addLayout(self.hl2)
        self.hl1.addLayout(self.vl3)
        self.vl1.addLayout(self.hl1)
        self.accept_cancel_box = QtWidgets.QDialogButtonBox(parent=AddCourseDialog)
        self.accept_cancel_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.accept_cancel_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.accept_cancel_box.setObjectName("accept_cancel_box")
        self.vl1.addWidget(self.accept_cancel_box)

        self.retranslateUi(AddCourseDialog)
        self.accept_cancel_box.accepted.connect(AddCourseDialog.accept) # type: ignore
        self.accept_cancel_box.rejected.connect(AddCourseDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddCourseDialog)

    def retranslateUi(self, AddCourseDialog):
        _translate = QtCore.QCoreApplication.translate
        AddCourseDialog.setWindowTitle(_translate("AddCourseDialog", "Add Course"))
        self.lb_cname.setText(_translate("AddCourseDialog", "Name"))
        self.lb_cduration_2.setText(_translate("AddCourseDialog", "Duration"))
        self.sb_duration.setSuffix(_translate("AddCourseDialog", " min"))
