# Form implementation generated from reading ui file 'D:\Coding\Teachart\designer\ui_add_student.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddStudentDialog(object):
    def setupUi(self, AddStudentDialog):
        AddStudentDialog.setObjectName("AddStudentDialog")
        AddStudentDialog.resize(310, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddStudentDialog.sizePolicy().hasHeightForWidth())
        AddStudentDialog.setSizePolicy(sizePolicy)
        AddStudentDialog.setMinimumSize(QtCore.QSize(310, 150))
        AddStudentDialog.setMaximumSize(QtCore.QSize(310, 150))
        self.vl1 = QtWidgets.QVBoxLayout(AddStudentDialog)
        self.vl1.setObjectName("vl1")
        self.hl1 = QtWidgets.QHBoxLayout()
        self.hl1.setObjectName("hl1")
        self.vl2 = QtWidgets.QVBoxLayout()
        self.vl2.setContentsMargins(-1, -1, 10, -1)
        self.vl2.setObjectName("vl2")
        self.lb_name = QtWidgets.QLabel(parent=AddStudentDialog)
        self.lb_name.setObjectName("lb_name")
        self.vl2.addWidget(self.lb_name)
        self.lb_course = QtWidgets.QLabel(parent=AddStudentDialog)
        self.lb_course.setObjectName("lb_course")
        self.vl2.addWidget(self.lb_course)
        self.lb_email = QtWidgets.QLabel(parent=AddStudentDialog)
        self.lb_email.setObjectName("lb_email")
        self.vl2.addWidget(self.lb_email)
        self.hl1.addLayout(self.vl2)
        self.vl3 = QtWidgets.QVBoxLayout()
        self.vl3.setObjectName("vl3")
        self.le_name = QtWidgets.QLineEdit(parent=AddStudentDialog)
        self.le_name.setMinimumSize(QtCore.QSize(0, 30))
        self.le_name.setObjectName("le_name")
        self.vl3.addWidget(self.le_name)
        self.cb_courses = QtWidgets.QComboBox(parent=AddStudentDialog)
        self.cb_courses.setMinimumSize(QtCore.QSize(0, 30))
        self.cb_courses.setModelColumn(1)
        self.cb_courses.setObjectName("cb_courses")
        self.vl3.addWidget(self.cb_courses)
        self.le_email = QtWidgets.QLineEdit(parent=AddStudentDialog)
        self.le_email.setMinimumSize(QtCore.QSize(0, 30))
        self.le_email.setObjectName("le_email")
        self.vl3.addWidget(self.le_email)
        self.hl1.addLayout(self.vl3)
        self.vl1.addLayout(self.hl1)
        self.button_box = QtWidgets.QDialogButtonBox(parent=AddStudentDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.vl1.addWidget(self.button_box)

        self.retranslateUi(AddStudentDialog)
        self.cb_courses.setCurrentIndex(-1)
        self.button_box.accepted.connect(AddStudentDialog.accept) # type: ignore
        self.button_box.rejected.connect(AddStudentDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddStudentDialog)

    def retranslateUi(self, AddStudentDialog):
        _translate = QtCore.QCoreApplication.translate
        AddStudentDialog.setWindowTitle(_translate("AddStudentDialog", "Add Student"))
        self.lb_name.setText(_translate("AddStudentDialog", "Name"))
        self.lb_course.setText(_translate("AddStudentDialog", "Course"))
        self.lb_email.setText(_translate("AddStudentDialog", "E-Mail"))
