# Form implementation generated from reading ui file 'D:\Coding\Teachart\designer\ui_debug_xml.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_xml_dialog(object):
    def setupUi(self, xml_dialog):
        xml_dialog.setObjectName("xml_dialog")
        xml_dialog.resize(488, 380)
        xml_dialog.setWindowTitle("XML Inspector")
        xml_dialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(xml_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tw_xmls = QtWidgets.QTabWidget(parent=xml_dialog)
        self.tw_xmls.setObjectName("tw_xmls")
        self.structure_tab = QtWidgets.QWidget()
        self.structure_tab.setObjectName("structure_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.structure_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tb_structure = QtWidgets.QTextBrowser(parent=self.structure_tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.tb_structure.setFont(font)
        self.tb_structure.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.tb_structure.setOpenLinks(False)
        self.tb_structure.setObjectName("tb_structure")
        self.verticalLayout_2.addWidget(self.tb_structure)
        self.tw_xmls.addTab(self.structure_tab, "")
        self.resources_tab = QtWidgets.QWidget()
        self.resources_tab.setObjectName("resources_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.resources_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tb_resources = QtWidgets.QTextBrowser(parent=self.resources_tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.tb_resources.setFont(font)
        self.tb_resources.setObjectName("tb_resources")
        self.verticalLayout_3.addWidget(self.tb_resources)
        self.tw_xmls.addTab(self.resources_tab, "")
        self.verticalLayout.addWidget(self.tw_xmls)

        self.retranslateUi(xml_dialog)
        self.tw_xmls.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(xml_dialog)

    def retranslateUi(self, xml_dialog):
        _translate = QtCore.QCoreApplication.translate
        self.tb_structure.setHtml(_translate("xml_dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tw_xmls.setTabText(self.tw_xmls.indexOf(self.structure_tab), _translate("xml_dialog", "structure"))
        self.tw_xmls.setTabText(self.tw_xmls.indexOf(self.resources_tab), _translate("xml_dialog", "resources"))
