# Form implementation generated from reading ui file 'D:\Coding\Teachart\designer\ui_debug_table.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TableInspector(object):
    def setupUi(self, TableInspector):
        TableInspector.setObjectName("TableInspector")
        TableInspector.resize(665, 520)
        self.verticalLayout = QtWidgets.QVBoxLayout(TableInspector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tv_table = QtWidgets.QTreeView(parent=TableInspector)
        self.tv_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.CurrentChanged|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed)
        self.tv_table.setAlternatingRowColors(True)
        self.tv_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tv_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.tv_table.setObjectName("tv_table")
        self.verticalLayout.addWidget(self.tv_table)

        self.retranslateUi(TableInspector)
        QtCore.QMetaObject.connectSlotsByName(TableInspector)

    def retranslateUi(self, TableInspector):
        _translate = QtCore.QCoreApplication.translate
        TableInspector.setWindowTitle(_translate("TableInspector", "Table Inspector"))
