# Form implementation generated from reading ui file 'D:\Coding\Teachart\designer\ui_debug_resources.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ResourcesView(object):
    def setupUi(self, ResourcesView):
        ResourcesView.setObjectName("ResourcesView")
        ResourcesView.resize(581, 471)
        self.verticalLayout = QtWidgets.QVBoxLayout(ResourcesView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tv_robjects = QtWidgets.QTreeView(parent=ResourcesView)
        self.tv_robjects.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tv_robjects.setProperty("showDropIndicator", False)
        self.tv_robjects.setAlternatingRowColors(True)
        self.tv_robjects.setRootIsDecorated(False)
        self.tv_robjects.setItemsExpandable(False)
        self.tv_robjects.setSortingEnabled(True)
        self.tv_robjects.setExpandsOnDoubleClick(False)
        self.tv_robjects.setObjectName("tv_robjects")
        self.verticalLayout.addWidget(self.tv_robjects)

        self.retranslateUi(ResourcesView)
        QtCore.QMetaObject.connectSlotsByName(ResourcesView)

    def retranslateUi(self, ResourcesView):
        _translate = QtCore.QCoreApplication.translate
        ResourcesView.setWindowTitle(_translate("ResourcesView", "Resources View"))
