# Form implementation generated from reading ui file 'designer/ui_debug_xml.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_XMLInspector(object):
    def setupUi(self, XMLInspector):
        XMLInspector.setObjectName("XMLInspector")
        XMLInspector.resize(488, 380)
        XMLInspector.setWindowTitle("XML Inspector")
        XMLInspector.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(XMLInspector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tw_xmls = QtWidgets.QTabWidget(parent=XMLInspector)
        self.tw_xmls.setObjectName("tw_xmls")
        self.structure_tab = QtWidgets.QWidget()
        self.structure_tab.setObjectName("structure_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.structure_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tb_structure = QtWidgets.QTextBrowser(parent=self.structure_tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.tb_structure.setFont(font)
        self.tb_structure.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.tb_structure.setOpenLinks(False)
        self.tb_structure.setObjectName("tb_structure")
        self.verticalLayout_2.addWidget(self.tb_structure)
        self.tw_xmls.addTab(self.structure_tab, "structure")
        self.lesson_tab = QtWidgets.QWidget()
        self.lesson_tab.setObjectName("lesson_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.lesson_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tb_lesson = QtWidgets.QTextBrowser(parent=self.lesson_tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.tb_lesson.setFont(font)
        self.tb_lesson.setObjectName("tb_lesson")
        self.verticalLayout_3.addWidget(self.tb_lesson)
        self.tw_xmls.addTab(self.lesson_tab, "lesson")
        self.metadata_tab = QtWidgets.QWidget()
        self.metadata_tab.setObjectName("metadata_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.metadata_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tb_metadata = QtWidgets.QTextBrowser(parent=self.metadata_tab)
        self.tb_metadata.setObjectName("tb_metadata")
        self.verticalLayout_4.addWidget(self.tb_metadata)
        self.tw_xmls.addTab(self.metadata_tab, "metadata")
        self.verticalLayout.addWidget(self.tw_xmls)

        self.retranslateUi(XMLInspector)
        self.tw_xmls.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(XMLInspector)

    def retranslateUi(self, XMLInspector):
        _translate = QtCore.QCoreApplication.translate
        self.tb_structure.setHtml(_translate("XMLInspector", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
