# Form implementation generated from reading ui file 'D:\Coding\Teachart\designer\ui_record_view.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RecordDialog(object):
    def setupUi(self, RecordDialog):
        RecordDialog.setObjectName("RecordDialog")
        RecordDialog.resize(434, 251)
        self.verticalLayout = QtWidgets.QVBoxLayout(RecordDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tv_students = QtWidgets.QTreeView(parent=RecordDialog)
        self.tv_students.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tv_students.setAlternatingRowColors(True)
        self.tv_students.setUniformRowHeights(True)
        self.tv_students.setWordWrap(True)
        self.tv_students.setObjectName("tv_students")
        self.verticalLayout.addWidget(self.tv_students)
        self.hl1 = QtWidgets.QHBoxLayout()
        self.hl1.setContentsMargins(-1, 10, -1, -1)
        self.hl1.setObjectName("hl1")
        self.pb_edit = QtWidgets.QPushButton(parent=RecordDialog)
        self.pb_edit.setObjectName("pb_edit")
        self.hl1.addWidget(self.pb_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hl1.addItem(spacerItem)
        self.pb_close = QtWidgets.QPushButton(parent=RecordDialog)
        self.pb_close.setObjectName("pb_close")
        self.hl1.addWidget(self.pb_close)
        self.verticalLayout.addLayout(self.hl1)

        self.retranslateUi(RecordDialog)
        QtCore.QMetaObject.connectSlotsByName(RecordDialog)

    def retranslateUi(self, RecordDialog):
        _translate = QtCore.QCoreApplication.translate
        RecordDialog.setWindowTitle(_translate("RecordDialog", "Dialog"))
        self.pb_edit.setText(_translate("RecordDialog", "Edit"))
        self.pb_close.setText(_translate("RecordDialog", "Close"))
