# Form implementation generated from reading ui file 'C:/Users/Florian/AppData/Local/Temp/darkSHtaYs.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtCore import (
    QCoreApplication,
    QDateTime,
    QLocale,
    QMetaObject,
    QSize,
    Qt,
)
from PyQt6.QtGui import QAction, QActionGroup, QKeySequence
from PyQt6.QtWidgets import (
    QAbstractSpinBox,
    QButtonGroup,
    QDateTimeEdit,
    QDockWidget,
    QFrame,
    QHBoxLayout,
    QLabel,
    QMainWindow,
    QMenu,
    QMenuBar,
    QSizePolicy,
    QSpacerItem,
    QSpinBox,
    QStatusBar,
    QStyle,
    QToolBar,
    QToolButton,
    QVBoxLayout,
    QWidget,
)

from nativeelements.baseelement import BaseElementDefinitions, BaseElementToolset
from tcha.consts import CanvasTool
from tcha.settings import Locale, Settings, TimeFormat
from tcha.styling import Svg, SvgIcon
from tcha.table import PresenterCanvas, Table
from ui.commons import NoteEdit, SearchableComboBox, SwitchAction


class Ui_Editor(object):
    def setupUi(self, MainWindow: QMainWindow):
        MainWindow.setObjectName("EditorView")
        MainWindow.resize(850, 500)
        MainWindow.setDocumentMode(True)
        MainWindow.setDockOptions(
            QMainWindow.DockOption.AllowTabbedDocks
            | QMainWindow.DockOption.AnimatedDocks
            | QMainWindow.DockOption.ForceTabbedDocks
            | QMainWindow.DockOption.VerticalTabs
        )
        self.centralwidget = QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vl2 = QVBoxLayout(self.centralwidget)
        self.vl2.setObjectName("vl2")

        self.table = Table(self.centralwidget)
        self.table.setObjectName("Table")
        self.vl2.addWidget(self.table)

        MainWindow.setCentralWidget(self.centralwidget)

        qsettings = Settings.qsettings()

        # Menu bar

        self.menubar = QMenuBar(parent=MainWindow)
        self.menubar.setContentsMargins(0, 0, 0, 0)
        self.menubar.setMaximumHeight(28)
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menu_file = QMenu(parent=self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_edit = QMenu(parent=self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu_elements = QMenu(self.menubar)
        self.menu_elements.setObjectName("menu_elements")
        self.menu_elements.setEnabled(False)
        self.menu_view = QMenu(parent=self.menubar)
        self.menu_view.setObjectName("menu_view")
        self.menu_opt = QMenu(parent=self.menubar)
        self.menu_opt.setObjectName("menu_opt")
        self.menu_debug = QMenu(parent=self.menubar)
        self.menu_debug.setObjectName("menu_debug")

        if qsettings.value("Application/debug", False, bool):
            self.menu_debug.setVisible(False)

        self.menuHelp = QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")

        # Corner Widget at right side of menu bar

        self.corner_widget = QWidget(MainWindow)
        self.corner_widget.setMaximumHeight(25)
        cw_layout = QHBoxLayout(self.corner_widget)
        cw_layout.setContentsMargins(0, 0, 0, 0)
        self.corner_widget.setLayout(cw_layout)

        self.tb_open = QToolButton(MainWindow)
        icon10 = MainWindow.style().standardIcon(QStyle.StandardPixmap.SP_DirIcon)
        self.tb_open.setIcon(icon10)
        cw_layout.addWidget(self.tb_open)

        self.tb_save = QToolButton(MainWindow)
        icon9 = MainWindow.style().standardIcon(
            QStyle.StandardPixmap.SP_DialogSaveButton
        )
        self.tb_save.setIcon(icon9)
        cw_layout.addWidget(self.tb_save)

        self.menubar.setCornerWidget(self.corner_widget, Qt.Corner.TopRightCorner)
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.statusbar.setMaximumHeight(25)

        self.lb_row = QLabel(parent=MainWindow)
        self.lb_row.setObjectName("lb_row")
        self.statusbar.addWidget(self.lb_row)

        self.row_list = self.table.row_list
        self.row_list.setStyleSheet(
            """QComboBox {
                padding: 0 0 0 2px; 
                min-height: 1.1em; 
                border: 1px
                }
                
                QComboBox::down-arrow {image: none}"""
        )
        self.row_list.setMaximumWidth(35)
        self.row_list.view().setFixedWidth(50)
        self.statusbar.addWidget(self.row_list)

        self.tb_row_down = QToolButton(self.statusbar)
        self.tb_row_down.setObjectName("tb_row_down")
        icon20 = SvgIcon("resources/icons/ic_down.svg")
        self.tb_row_down.setIcon(icon20)
        self.statusbar.addWidget(self.tb_row_down)

        self.tb_row_up = QToolButton(self.statusbar)
        self.tb_row_up.setObjectName("tb_row_up")
        icon21 = SvgIcon("resources/icons/ic_up.svg")
        self.tb_row_up.setIcon(icon21)
        self.statusbar.addWidget(self.tb_row_up)

        line1 = QFrame(parent=MainWindow)
        line1.setFrameShape(QFrame.Shape.VLine)
        line1.setFrameShadow(QFrame.Shadow.Plain)
        line1.setObjectName("line1")
        self.statusbar.addWidget(line1)

        MainWindow.setStatusBar(self.statusbar)

        # Dock Widgets: PresenterCanvas and Notes

        self.dw_presenter = QDockWidget(parent=MainWindow)
        self.dw_presenter.setEnabled(False)
        self.dw_presenter.setFeatures(
            QDockWidget.DockWidgetFeature.DockWidgetMovable
            | QDockWidget.DockWidgetFeature.DockWidgetFloatable
        )
        self.dw_presenter.setAllowedAreas(
            Qt.DockWidgetArea.LeftDockWidgetArea
            | Qt.DockWidgetArea.RightDockWidgetArea
            | Qt.DockWidgetArea.BottomDockWidgetArea
        )
        self.dw_presenter.setObjectName("dw_presenter")
        self.dw_presenter.hide()

        self.widget_dw_contents2 = QWidget()
        self.widget_dw_contents2.setObjectName("widget_dw_contents2")

        self.dw_lo2 = QVBoxLayout(self.widget_dw_contents2)
        self.dw_lo2.setObjectName("dw_lo2")

        self.dw_lo3 = QHBoxLayout()
        self.dw_lo3.setObjectName("dw_lo3")

        self.bg_tools = QButtonGroup()

        # self.tb_pointer = QToolButton(self.widget_dw_contents2)
        # self.tb_pointer.setObjectName("tb_pointer")
        # self.tb_pointer.setCheckable(True)
        # self.tb_pointer.setChecked(True)
        # self.tb_pointer.setProperty("tool", CanvasTool.Pointer)
        # icon19 = SvgIcon("resources/icons/ic_pointer.svg")
        # self.tb_pointer.setIcon(icon19)
        # self.dw_lo3.addWidget(self.tb_pointer)
        # self.bg_tools.addButton(self.tb_pointer)

        self.tb_pen = QToolButton(self.widget_dw_contents2)
        self.tb_pen.setObjectName("tb_pen")
        self.tb_pen.setCheckable(True)
        self.tb_pen.setChecked(True)
        self.tb_pen.setProperty("tool", CanvasTool.Pen)
        icon16 = SvgIcon("resources/icons/ic_pen.svg")
        self.tb_pen.setIcon(icon16)
        self.dw_lo3.addWidget(self.tb_pen)
        self.bg_tools.addButton(self.tb_pen)

        self.tb_arrow = QToolButton(self.widget_dw_contents2)
        self.tb_arrow.setObjectName("tb_arrow")
        self.tb_arrow.setCheckable(True)
        self.tb_arrow.setProperty("tool", CanvasTool.Arrow)
        icon18 = SvgIcon("resources/icons/ic_arrowTool.svg")
        self.tb_arrow.setIcon(icon18)
        self.dw_lo3.addWidget(self.tb_arrow)
        self.bg_tools.addButton(self.tb_arrow)

        self.tb_rubber = QToolButton(self.widget_dw_contents2)
        self.tb_rubber.setObjectName("tb_rubber")
        self.tb_rubber.setCheckable(True)
        self.tb_rubber.setProperty("tool", CanvasTool.Rubber)
        icon17 = SvgIcon("resources/icons/ic_rubber.svg")
        self.tb_rubber.setIcon(icon17)
        self.dw_lo3.addWidget(self.tb_rubber)
        self.bg_tools.addButton(self.tb_rubber)

        self.dw_lo3.addSpacing(5)

        self.bg_colors = QButtonGroup()

        tb_style = """
        QToolButton {
            min-width: 14px;
            min-height: 14px;
            max-width: 14px;
            max-height: 14px;
            border: 1px solid black;
            border-radius: 7px; 
            padding: 0px; 
            margin: 1px; 
            background-color: [color];
            }

        QToolButton:checked, QToolButton:hover {
            min-width: 16px;
            min-height: 16px;
            max-width: 16px;
            max-height: 16px;
            border: 1px solid black;
            border-radius: 8px;
            padding: 0px;
            margin: 0px;
            }
        """

        self.tb_red = QToolButton(self.widget_dw_contents2)
        self.tb_red.setObjectName("tb_red")
        self.tb_red.setCheckable(True)
        self.tb_red.setChecked(True)
        # self.tb_red.setFixedSize(16, 16)
        style1 = tb_style.replace("[color]", "red")
        self.tb_red.setStyleSheet(style1)
        self.tb_red.setProperty("color", Qt.GlobalColor.red)
        self.dw_lo3.addWidget(self.tb_red)
        self.bg_colors.addButton(self.tb_red)

        self.tb_blue = QToolButton(self.widget_dw_contents2)
        self.tb_blue.setObjectName("tb_blue")
        self.tb_blue.setCheckable(True)
        # self.tb_blue.setFixedSize(16, 16)
        style2 = tb_style.replace("[color]", "blue")
        self.tb_blue.setStyleSheet(style2)
        self.tb_blue.setProperty("color", Qt.GlobalColor.blue)
        self.dw_lo3.addWidget(self.tb_blue)
        self.bg_colors.addButton(self.tb_blue)

        self.tb_yellow = QToolButton(self.widget_dw_contents2)
        self.tb_yellow.setObjectName("tb_yellow")
        self.tb_yellow.setCheckable(True)
        # self.tb_yellow.setFixedSize(16, 16)
        style3 = tb_style.replace("[color]", "yellow")
        self.tb_yellow.setStyleSheet(style3)
        self.tb_yellow.setProperty("color", Qt.GlobalColor.darkYellow)
        self.dw_lo3.addWidget(self.tb_yellow)
        self.bg_colors.addButton(self.tb_yellow)

        spa2 = QSpacerItem(100, 18, QSizePolicy.Policy.Expanding)
        self.dw_lo3.addItem(spa2)

        self.dw_lo2.addLayout(self.dw_lo3)

        self.canvas = PresenterCanvas()
        self.canvas.setObjectName("canvas")
        self.canvas.setCursor(Qt.CursorShape.CrossCursor)

        self.dw_lo2.addWidget(self.canvas)
        self.dw_presenter.setWidget(self.widget_dw_contents2)
        MainWindow.addDockWidget(
            Qt.DockWidgetArea.RightDockWidgetArea, self.dw_presenter
        )

        self.dw_comment = QDockWidget(parent=MainWindow)
        self.dw_comment.setEnabled(True)
        self.dw_comment.setMinimumSize(QSize(100, 155))
        self.dw_comment.setFeatures(
            QDockWidget.DockWidgetFeature.DockWidgetClosable
            | QDockWidget.DockWidgetFeature.DockWidgetMovable
        )
        self.dw_comment.setAllowedAreas(
            Qt.DockWidgetArea.LeftDockWidgetArea
            | Qt.DockWidgetArea.RightDockWidgetArea
            | Qt.DockWidgetArea.TopDockWidgetArea
        )
        self.dw_comment.setObjectName("dw_comment")

        self.widget_dw_contents = QWidget()
        self.widget_dw_contents.setObjectName("widget_dw_contents")

        self.dw_lo1 = QVBoxLayout(self.widget_dw_contents)
        self.dw_lo1.setObjectName("dw_lo1")

        self.dw_lo4 = QHBoxLayout()
        self.dw_lo4.setObjectName("dw_lo4")

        self.tb_link = QToolButton(self.widget_dw_contents)
        self.tb_link.setObjectName("tb_link")

        self.te_comment = NoteEdit(parent=self.widget_dw_contents)
        self.te_comment.setMinimumSize(QSize(100, 100))
        self.te_comment.setObjectName("te_comment")

        self.dw_lo1.addWidget(self.te_comment)
        self.dw_comment.setWidget(self.widget_dw_contents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dw_comment)

        # Tool Bars

        self.tb_lesson = QToolBar(parent=MainWindow)
        self.tb_lesson.setEnabled(True)
        self.tb_lesson.setMovable(False)
        self.tb_lesson.setIconSize(QSize(22, 22))
        self.tb_lesson.setObjectName("tb_lesson")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.tb_lesson)

        self.tb_table = QToolBar(parent=MainWindow)
        self.tb_table.setAllowedAreas(Qt.ToolBarArea.TopToolBarArea)
        self.tb_table.setIconSize(QSize(22, 22))
        self.tb_table.setFloatable(False)
        self.tb_table.setObjectName("tb_table")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.tb_table)
        MainWindow.insertToolBarBreak(self.tb_table)

        self.tb_cell = QToolBar(parent=MainWindow)
        self.tb_cell.setAllowedAreas(
            Qt.ToolBarArea.LeftToolBarArea
            | Qt.ToolBarArea.RightToolBarArea
            | Qt.ToolBarArea.TopToolBarArea
        )
        self.tb_cell.setIconSize(QSize(22, 22))
        self.tb_cell.setFloatable(False)
        self.tb_cell.setObjectName("tb_cell")
        self.tb_cell.hide()
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.tb_cell)

        # File actions

        self.ac_new_doc = QAction(parent=MainWindow)
        self.ac_new_doc.setObjectName("ac_new_doc")
        self.ac_new_doc.setShortcut(QKeySequence.StandardKey.New)
        self.ac_open_doc = QAction(parent=MainWindow)
        self.ac_open_doc.setObjectName("ac_open_doc")
        self.ac_open_doc.setIcon(icon10)
        self.ac_open_doc.setShortcut(QKeySequence.StandardKey.Open)
        self.ac_recent = QAction(parent=MainWindow)
        self.ac_recent.setObjectName("ac_recent")
        self.ac_scheduledf = QAction(parent=MainWindow)  # Unused
        self.ac_scheduledf.setObjectName("ac_scheduledf")  # Unused
        self.ac_save = QAction(parent=MainWindow)
        self.ac_save.setObjectName("ac_save")
        self.ac_save.setIcon(icon9)
        self.ac_save.setShortcut(QKeySequence.StandardKey.Save)
        self.ac_save_as = QAction(parent=MainWindow)
        self.ac_save_as.setObjectName("ac_save_as")
        self.ac_save_as.setShortcut(QKeySequence.StandardKey.SaveAs)
        self.ac_close = QAction(parent=MainWindow)
        self.ac_close.setObjectName("ac_close")
        self.ac_close.setShortcut(QKeySequence.StandardKey.Close)

        # Course Actions

        self.ac_add_course = QAction(parent=MainWindow)
        icon3 = SvgIcon("resources/icons/ic_new.svg")
        self.ac_add_course.setIcon(icon3)
        self.ac_add_course.setObjectName("ac_add_course")

        self.ac_course_exp = QAction(parent=MainWindow)
        self.ac_course_exp.setObjectName("ac_course_exp")
        self.ac_course_rec = QAction(parent=MainWindow)
        self.ac_course_rec.setObjectName("ac_course_rec")
        icon11 = SvgIcon("resources/icons/ic_info.svg")
        self.ac_course_rec.setIcon(icon11)

        icon12 = SvgIcon("resources/icons/ic_schedule.svg")
        icon13 = SvgIcon("resources/icons/ic_scheduled.svg")

        self.ac_schedule = SwitchAction(icon12, icon13, MainWindow)
        self.ac_schedule.setObjectName("ac_schedule")

        # View actions

        self.ac_show_notes = QAction(parent=MainWindow)
        self.ac_show_notes.setCheckable(True)
        self.ac_show_notes.setChecked(True)
        self.ac_show_notes.setObjectName("ac_show_notes")
        icon14 = SvgIcon("resources/icons/ic_notes.svg")
        self.ac_show_notes.setIcon(icon14)

        self.ac_pres_mode = QAction(parent=MainWindow)
        self.ac_pres_mode.setObjectName("ac_pres_mode")
        self.ac_pres_mode.setCheckable(True)
        self.ac_pres_mode.setChecked(False)
        self.ac_pres_mode.setShortcut(Qt.Key.Key_F11)
        icon15 = SvgIcon("resources/icons/ic_present_mode.svg")
        self.ac_pres_mode.setIcon(icon15)

        self.ac_show_ttbar = QAction(parent=MainWindow)
        self.ac_show_ttbar.setCheckable(True)
        self.ac_show_ttbar.setObjectName("ac_show_ttbar")

        # Debugging actions

        self.ac_file_insp = QAction(parent=MainWindow)
        self.ac_file_insp.setObjectName("ac_file_insp")
        self.ac_res_view = QAction(parent=MainWindow)
        self.ac_res_view.setObjectName("ac_res_view")
        self.ac_table_insp = QAction(parent=MainWindow)
        self.ac_table_insp.setObjectName("ac_table_insp")
        self.ac_xml_insp = QAction(parent=MainWindow)
        self.ac_xml_insp.setObjectName("ac_xml_insp")
        self.ac_xml_insp.setDisabled(True)

        # Table Actions

        # self.ac_new_table = QAction(parent=MainWindow)
        # self.ac_new_table.setObjectName("ac_new_table")

        self.ac_copy = QAction(parent=MainWindow)
        self.ac_copy.setObjectName("ac_copy")
        self.ac_copy.setDisabled(True)
        self.ac_copy.setShortcut(QKeySequence.StandardKey.Copy)
        self.ac_paste = QAction(parent=MainWindow)
        self.ac_paste.setObjectName("ac_paste")
        self.ac_paste.setDisabled(True)
        self.ac_paste.setShortcut(QKeySequence.StandardKey.Paste)

        self.table_group = QActionGroup(MainWindow)

        self.ac_add_to_cell = QAction(parent=MainWindow)
        icon = SvgIcon("resources/icons/ic_addblock.svg")
        self.ac_add_to_cell.setIcon(icon)
        self.ac_add_to_cell.setObjectName("ac_add_to_cell")
        self.table_group.addAction(self.ac_add_to_cell)

        self.elem_menu = QMenu()

        self.ac_from_clipboard = QAction(parent=MainWindow)
        self.ac_from_clipboard.setObjectName("ac_from_clipboard")
        self.ac_from_clipboard.setProperty("is_element_action", False)
        self.elem_menu.addAction(self.ac_from_clipboard)

        self.ac_add_to_cell.setMenu(self.elem_menu)

        self.ac_add_row = QAction(parent=MainWindow)
        icon1 = SvgIcon("resources/icons/ic_addrow.svg")
        self.ac_add_row.setIcon(icon1)
        self.ac_add_row.setObjectName("ac_add_row")
        self.table_group.addAction(self.ac_add_row)

        self.ac_add_column = QAction(parent=MainWindow)
        icon2 = SvgIcon("resources/icons/ic_addcolumn.svg")
        self.ac_add_column.setObjectName("ac_add_column")
        self.ac_add_column.setIcon(icon2)
        self.table_group.addAction(self.ac_add_column)

        self.ac_rmv_row = QAction(parent=MainWindow)
        icon4 = SvgIcon("resources/icons/ic_remove_row.svg")
        self.ac_rmv_row.setIcon(icon4)
        self.ac_rmv_row.setObjectName("ac_rmv_row")
        self.table_group.addAction(self.ac_rmv_row)

        self.ac_rmv_column = QAction(parent=MainWindow)
        icon5 = SvgIcon("resources/icons/ic_remove_column.svg")
        self.ac_rmv_column.setIcon(icon5)
        self.ac_rmv_column.setObjectName("ac_rmv_column")
        self.table_group.addAction(self.ac_rmv_column)

        self.table_group.setDisabled(True)

        self.ac_mov_up = QAction(parent=MainWindow)
        icon6 = SvgIcon("resources/icons/ic_move_up.svg")
        self.ac_mov_up.setIcon(icon6)
        self.ac_mov_up.setObjectName("ac_mov_up")
        self.ac_mov_dwn = QAction(parent=MainWindow)
        icon7 = SvgIcon("resources/icons/ic_move_down.svg")
        self.ac_mov_dwn.setIcon(icon7)
        self.ac_mov_dwn.setObjectName("ac_mov_dwn")
        self.ac_del_element = QAction(parent=MainWindow)
        icon8 = SvgIcon("resources/icons/ic_trash.svg")
        self.ac_del_element.setIcon(icon8)
        self.ac_del_element.setObjectName("ac_del_element")
        self.ac_clear_cell = QAction(parent=MainWindow)
        self.ac_clear_cell.setObjectName("ac_clear_cell")

        # Other Actions

        self.ac_settings = QAction(parent=MainWindow)
        self.ac_settings.setObjectName("ac_settings")

        self.ac_about = QAction(parent=MainWindow)
        self.ac_about.setObjectName("ac_about")
        icon19 = SvgIcon("resources/icons/ic_about.svg")
        self.ac_about.setIcon(icon19)

        # Menu Definitions

        self.menu_file.addAction(self.ac_new_doc)
        self.menu_file.addAction(self.ac_open_doc)
        # self.menu_file.addAction(self.ac_recent)
        self.sep1 = self.menu_file.addSeparator()
        self.menu_file.addAction(self.ac_save)
        self.menu_file.addAction(self.ac_save_as)
        self.menu_file.addAction(self.ac_schedule)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.ac_close)
        self.menu_file.addSeparator()

        # self.menu_edit.addAction(self.ac_new_table)
        # self.menu_edit.addSeparator()
        self.menu_edit.addMenu(self.menu_elements)
        self.menu_edit.addAction(self.ac_copy)
        self.menu_edit.addAction(self.ac_paste)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.ac_add_row)
        self.menu_edit.addAction(self.ac_add_column)
        self.menu_edit.addAction(self.ac_rmv_row)
        self.menu_edit.addAction(self.ac_rmv_column)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.ac_clear_cell)

        self.menu_elements.addAction(self.ac_from_clipboard)

        self.menu_view.addAction(self.ac_pres_mode)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.ac_show_notes)
        # self.menu_view.addAction(self.ac_show_ttbar)

        self.menu_opt.addAction(self.ac_settings)
        self.menu_opt.addSeparator()
        self.menu_opt.addAction(self.ac_course_exp)
        self.menu_opt.addAction(self.ac_course_rec)
        self.menu_opt.addAction(self.ac_add_course)

        self.menu_debug.addAction(self.ac_file_insp)
        self.menu_debug.addAction(self.ac_res_view)
        self.menu_debug.addAction(self.ac_table_insp)
        self.menu_debug.addAction(self.ac_xml_insp)

        self.menuHelp.addAction(self.ac_about)

        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_opt.menuAction())
        self.menubar.addAction(self.menu_debug.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        # Construct Lesson Toolbar

        self.lb_course = QLabel("", MainWindow)
        self.tb_lesson.addWidget(self.lb_course)

        self.cb_course = SearchableComboBox(MainWindow)
        self.cb_course.setMinimumWidth(180)
        self.cb_course.setModelColumn(1)
        self.cb_course.lineEdit().setClearButtonEnabled(True)
        self.tb_lesson.addWidget(self.cb_course)

        self.tb_lesson.addAction(self.ac_add_course)
        self.tb_lesson.addAction(self.ac_course_rec)
        self.tb_lesson.addSeparator()

        self.lb_date_time = QLabel("", MainWindow)
        self.tb_lesson.addWidget(self.lb_date_time)

        qsettings = Settings.qsettings()
        self.dt_DateTime = QDateTimeEdit(MainWindow)
        locale = Locale[qsettings.value("User/language", type=str)].value
        tformat = TimeFormat[qsettings.value("User/time_format", type=str)].value
        qlocale = QLocale(locale.language, locale.region)
        self.dt_DateTime.setLocale(qlocale)
        self.dt_DateTime.setDisplayFormat(
            f"{qlocale.dateFormat(QLocale.FormatType.ShortFormat)} {tformat}"
        )
        self.dt_DateTime.setMinimumWidth(155)
        self.dt_DateTime.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.dt_DateTime.setProperty("showGroupSeparator", False)
        self.dt_DateTime.setCalendarPopup(True)
        self.dt_DateTime.setObjectName("DT_DateTime")
        self.dt_DateTime.setDateTime(QDateTime.currentDateTime())
        self.tb_lesson.addWidget(self.dt_DateTime)

        self.tb_lesson.addAction(self.ac_schedule)

        self.tb_lesson.addSeparator()

        self.lb_duration = QLabel("", MainWindow)
        self.tb_lesson.addWidget(self.lb_duration)

        self.sb_duration = QSpinBox(MainWindow)
        self.sb_duration.setObjectName("sb_duration")
        self.sb_duration.setMaximum(255)
        self.tb_lesson.addWidget(self.sb_duration)

        spa = QWidget(self.tb_lesson)
        spa.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        self.tb_lesson.addWidget(spa)

        self.tb_lesson.addAction(self.ac_pres_mode)
        self.tb_lesson.addAction(self.ac_show_notes)

        # Construct Table Tool Bar

        self.tb_table.addAction(self.ac_add_to_cell)
        widget: QToolButton = self.tb_table.widgetForAction(self.ac_add_to_cell)
        widget.setMenu(self.menu_elements)
        widget.setPopupMode(QToolButton.ToolButtonPopupMode.InstantPopup)
        self.tb_table.addAction(self.ac_add_row)
        self.tb_table.addAction(self.ac_add_column)
        self.tb_table.addSeparator()
        self.tb_table.addAction(self.ac_rmv_row)
        self.tb_table.addAction(self.ac_rmv_column)
        self.tb_cell.addAction(self.ac_mov_up)
        self.tb_cell.addAction(self.ac_mov_dwn)
        self.tb_cell.addAction(self.ac_del_element)
        self.tb_cell.hide()

        self.retranslateUi(MainWindow)
        self.ac_show_notes.toggled["bool"].connect(self.dw_comment.setVisible)  # type: ignore
        self.dw_presenter.visibilityChanged["bool"].connect(
            self.ac_pres_mode.setChecked
        )
        self.dw_comment.visibilityChanged["bool"].connect(self.ac_show_notes.setChecked)  # type: ignore
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.menu_edit.setTitle(_translate("MainWindow", "Edit"))
        self.menu_elements.setTitle(_translate("MainWindow", "Add To Cell"))
        self.menu_view.setTitle(_translate("MainWindow", "View"))
        self.menu_opt.setTitle(_translate("MainWindow", "Options"))
        self.menu_debug.setTitle(_translate("MainWindow", "Debugging"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.dw_presenter.setWindowTitle(_translate("MainWindow", "Presentation View"))
        self.dw_comment.setWindowTitle(_translate("MainWindow", "Notes"))
        self.tb_lesson.setWindowTitle(_translate("MainWindow", "Lesson Details"))
        self.tb_table.setWindowTitle(_translate("MainWindow", "Table Tools"))
        self.tb_cell.setWindowTitle(_translate("MainWindow", "Cell Tools"))
        self.ac_add_to_cell.setText(_translate("MainWindow", "Add to Cell"))
        self.ac_from_clipboard.setText(_translate("MainWindow", "From Clipboard"))
        self.ac_add_row.setText(_translate("MainWindow", "Add Row"))
        self.ac_add_column.setText(_translate("MainWindow", "Add Column"))
        self.ac_new_doc.setText(_translate("MainWindow", "New"))
        self.ac_open_doc.setText(_translate("MainWindow", "Open"))
        self.ac_recent.setText(_translate("MainWindow", "Recent Files"))
        self.ac_save.setText(_translate("MainWindow", "Save"))
        self.ac_save_as.setText(_translate("MainWindow", "Save as"))
        self.ac_close.setText(_translate("MainWindow", "Close"))
        # self.ac_new_table.setText(_translate("MainWindow", "New Table"))
        # self.ac_new_table.setToolTip(
        #     _translate("MainWindow", "Reset and create a new table")
        # )
        self.ac_pres_mode.setText(_translate("MainWindow", "Presentation Mode"))
        self.ac_settings.setText(_translate("MainWindow", "Settings"))
        self.ac_course_exp.setText(_translate("MainWindow", "Course Explorer"))
        self.ac_course_rec.setText(_translate("MainWindow", "View Course Record"))
        self.ac_file_insp.setText(_translate("MainWindow", "File Inspector"))
        self.ac_about.setText(_translate("MainWindow", "About Teachart"))
        self.ac_res_view.setText(_translate("MainWindow", "Resource View"))
        self.ac_table_insp.setText(_translate("MainWindow", "Table Inspector"))
        self.ac_xml_insp.setText(_translate("MainWindow", "XML Inspector"))
        self.ac_schedule.setText(_translate("MainWindow", "Schedule"))
        self.ac_copy.setText(_translate("MainWindow", "Copy "))
        self.ac_paste.setText(_translate("MainWindow", "Paste"))
        self.ac_show_notes.setText(_translate("MainWindow", "Show Notes"))
        self.ac_show_ttbar.setText(_translate("MainWindow", "Show Table Tool Bar"))
        self.ac_add_course.setText(_translate("MainWindow", "New Course"))
        self.ac_rmv_row.setText(_translate("MainWindow", "Remove Row"))
        self.ac_rmv_column.setText(_translate("MainWindow", "Remove Column"))
        self.ac_scheduledf.setText(_translate("MainWindow", "Today's Scheduled Files"))
        self.ac_mov_up.setText(_translate("MainWindow", "Move Up"))
        self.ac_mov_dwn.setText(_translate("MainWindow", "Move Down"))
        self.ac_mov_dwn.setToolTip(_translate("MainWindow", "Move Down"))
        self.ac_del_element.setText(_translate("MainWindow", "Delete Element"))
        self.ac_clear_cell.setText(_translate("MainWindow", "Clear Cell"))

        self.tb_arrow.setToolTip(
            _translate(
                "MainWindow",
                "Draw Arrow - Drag the cursor while holding the mouse button and release for the arrow tip",
            )
        )
        self.tb_rubber.setToolTip(_translate("MainWindow", "Rubber"))
        self.tb_pen.setToolTip(_translate("MainWindow", "Pen"))
        self.tb_red.setToolTip(_translate("MainWindow", "Red"))
        self.tb_blue.setToolTip(_translate("MainWindow", "Blue"))
        self.tb_yellow.setToolTip(_translate("MainWindow", "Dark yellow"))

        self.lb_course.setText(_translate("MainWindow", "Course"))
        self.lb_date_time.setText(_translate("MainWindow", "Date/Time"))
        self.lb_duration.setText(_translate("MainWindow", "Duration"))
        self.lb_row.setText(_translate("MainWindow", "Top row"))

        self.sb_duration.setSuffix(_translate("MainWindow", " min"))

    def add_element_actions(
        self, edefinitions: dict[str, BaseElementDefinitions]
    ) -> None:
        for key in edefinitions.keys():
            action = edefinitions[key].action(self.menu_elements)
            print("Add Action from element", action.data())
            self.menu_elements.addAction(action)
            print("Current menu actions", self.menu_elements.actions())

    def add_toolsets(
        self, window: QMainWindow, edefinitions: dict[str, BaseElementDefinitions]
    ) -> dict[str, BaseElementToolset]:
        d = {}
        for key in edefinitions.keys():
            toolset = edefinitions[key].toolset(window)
            window.addToolBar(Qt.ToolBarArea.TopToolBarArea, toolset)
            toolset.setVisible(False)
            toolset.visibilityChanged.connect(self.on_element_toolbar_visibilty_changed)
            d[key] = toolset
        return d

    def on_element_toolbar_visibilty_changed(self, open: bool) -> None:
        self.tb_cell.setVisible(open)
        self.tb_table.setVisible(not open)
