from PyQt6 import QtWidgets, QtCore, QtGui
from ui.StyledWidget import fromStyle

class MainView(QtWidgets.QMainWindow):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setUI()
        self.setWindowTitle("Educhart Indev")
        self.setStyleSheet(fromStyle("Common"))

    def setUI(self):
        self.setObjectName("MainWindow")
        self.resize(1100, 700)
        self.setMinimumSize(QtCore.QSize(1100, 0))
        self.central_widget = QtWidgets.QWidget(self)
        self.central_widget.setEnabled(True)
        self.central_widget.setObjectName("centralwidget")
        self.central_layout = QtWidgets.QVBoxLayout(self.central_widget)
        self.central_layout.setContentsMargins(0, 0, 0, 0)
        self.central_layout.setSpacing(0)
        self.central_layout.setObjectName("centralLayout")

        self.tab_widget = QtWidgets.QTabWidget(self.central_widget)
        # palette = QtGui.QPalette()
        # brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        # brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        # palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        # brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        # brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        # palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        # brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        # brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        # palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        # brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        # brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        # palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        # brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        # brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        # palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        # brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        # brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        # palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        # brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        # brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        # palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        # brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        # brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        # palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        # brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        # brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        # palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        # self.tab_widget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semilig")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        
        self.tab_widget.setFont(font)
        self.tab_widget.setStyleSheet(fromStyle("TabBar"))
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tab_widget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.tab_widget.setTabsClosable(True)
        self.tab_widget.setObjectName("tabWidget")

        self.central_layout.addWidget(self.tab_widget)
        self.setCentralWidget(self.central_widget)

        self.statusbar = QtWidgets.QStatusBar(self)
        self.setStatusBar(self.statusbar)