from __future__ import annotations

import argparse
import importlib.util as imputil
import json
import pprint
import zipfile
from pathlib import Path
from typing import Any, Type

from PyQt6.QtCore import QByteArray, QDataStream, QIODevice, qChecksum


def convert_to_bin(destination: Path, res_file: Path) -> int:
    if res_file.exists() and destination.suffix == ".bin":
        if res_file.suffix == ".py":
            spec = imputil.spec_from_file_location("resources", res_file.as_posix())
            module = imputil.module_from_spec(spec)
            spec.loader.exec_module(module)

            qt_resource_data: bytes = getattr(module, "qt_resource_data", b"")
            qt_resource_name: bytes = getattr(module, "qt_resource_name", b"")
            qt_resource_struct: bytes = getattr(module, "qt_resource_struct", b"")

        elif res_file.suffix in (".rcc", ".qrc"):
            print("Direct conversion of rcc or qrc files not supported yet")
            return 0

        else:
            print(f"Wrong resource file type: {res_file.suffix}. Must be '.py'")

        if all((qt_resource_data, qt_resource_name, qt_resource_struct)):
            bytearr = QByteArray()
            stream = QDataStream(bytearr, QIODevice.OpenModeFlag.WriteOnly)
            stream.writeBytes(b"tcha-qrc")
            stream.writeBytes(qt_resource_data)
            stream.writeBytes(qt_resource_name)
            stream.writeBytes(qt_resource_struct)

            chksum = qChecksum(bytearr)

            with open(destination, "wb") as f:
                f.write(bytearr.data())

            return chksum
        else:
            print(
                "Could not find one or either attributes: 'qt_resource_data', 'qt_resource_name', 'qt_resource_struct'"
            )

    return 0


def pack_theme(
    destination: Path, properties: Path, bin: Path, stylesheet: Path
) -> bool:
    """Packs the files under the given paths into a .taste-file at 'destination'. Returns True if the operation was successful"""
    try:
        if (
            destination.suffix == ".taste"
            and properties.suffix == ".json"
            and bin.suffix == ".bin"
            and stylesheet.suffix == ".qss"
        ):
            with open(properties.as_posix(), "r", encoding="utf-8") as json_f:
                json_properties = json.load(json_f)
            file = zipfile.ZipFile(destination.as_posix(), mode="w")
            file.write(properties.as_posix(), "properties.json")
            file.write(bin.as_posix(), json_properties["resources"])
            file.write(stylesheet.as_posix(), json_properties["stylesheet"])
            file.close()
            return True

        print(
            "Either one or more files have the wrong type: \ndestination : taste\nproperties : json\nresources : bin\nstylesheet : qss "
        )
        return False

    except KeyError as e:
        print(f"properties.json: File name for '{e.args}' could not be found.")
        return False
    except FileNotFoundError as e:
        print(f"File '{e.filename}' could not be found.")
        return False


def get_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="TPACK",
        description="Pack and organise taste-files for Techart",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    parser_pack = subparsers.add_parser("pack", help="Pack a taste-file ")
    parser_pack.add_argument(
        "paths",
        nargs=4,
        metavar="Paths",
        help="Arguments: [DESTINATION_PATH], [PROPERTIES_PATH],\n [RESOURCES_PATH] and [STYLESHEET_PATH]",
    )
    parser_pack.set_defaults(func=handle_pack)

    parser_bin = subparsers.add_parser(
        "bin", help="Convert resource python file generated by rcc into binary file"
    )
    parser_bin.add_argument(
        "paths",
        nargs=2,
        metavar="Paths",
        help="Arguments: [DESTINATION_PATH] [PY_FILE]",
    )
    parser_bin.set_defaults(func=handle_bin)

    parser_taste = subparsers.add_parser("taste", help="Edit taste-file")
    parser_taste.add_argument_group("taste", "Edit taste-file")

    parser_taste.add_argument(
        "path",
        type=str,
        help="The target path of the taste-file e.g.: taste [Path]",
    )

    parser_taste.add_argument(
        "--property",
        nargs="+",
        type=str,
        metavar=("KEY", "VALUE"),
        help="Specify a KEY to show the current value and optionally a VALUE to change the value of KEY.",
    )
    parser_taste.set_defaults(func=handle_taste)

    return parser


def handle_taste(namespace: argparse.Namespace) -> None:
    print(namespace)
    taste_file = Path(namespace.path)
    if taste_file.exists():
        zipf = zipfile.ZipFile(taste_file, "r")

        if hasattr(namespace, "property"):
            with zipf.open("properties.json", "r") as read_props:
                props: dict = json.load(read_props)
            new_props = handle_properties(props, namespace)

            print(zipf)
            zipf.close()

    else:
        print(f"'{e.filename}' could not be found.")


def handle_properties(props: dict, namespace: argparse.Namespace) -> dict:
    def prepare_value(val: str) -> Any:
        if val == "True":
            return True
        if val == "False":
            return False
        return val

    if namespace.property:
        key = namespace.property[0]
        if key == "colors":
            print("Value 'colors' cannot be changed")
            return props

        if len(namespace.property) == 1:
            pprint.pprint(props.get(key, "Key not existing"))
            return props

        elif len(namespace.property) == 2:
            if key not in ("palette", "colors") and props.get(key):
                value = prepare_value(namespace.property[1])
                val_type = type(props.get(key))
                try:
                    props[key] = val_type(value)
                    return props

                except (ValueError, TypeError):
                    print(f"Incorrect argument for key '{key}'")
                    return props
            else:
                print("Key not existing")
                return props

        else:
            print("Too many arguments. Only max. 2 allowed.")
            return props

    else:
        pprint.pprint(props)
        return props


def handle_bin(namespace: argparse.Namespace) -> None:
    destination, resources = map(lambda path: Path(path), namespace.paths)
    result = convert_to_bin(destination, resources)
    if result:
        print(f"Successfully converted to binary file. Checksum: {result}")
    else:
        print("Failed to convert")


def handle_pack(namespace: argparse.Namespace):
    destination, properties, resources, stylesheet = map(
        lambda path: Path(path), namespace.paths
    )
    print(f"Files: {destination}", properties, resources, stylesheet, sep=", ")
    result = pack_theme(
        destination.name, properties.name, resources.name, stylesheet.name
    )
    if result:
        print("Successfully composed taste-file")
    else:
        print("Failed to compose taste-file")


def main():
    parser = get_parser()
    args = parser.parse_args()
    if hasattr(args, "func"):
        args.func(args)


if __name__ == "__main__":
    main()
