from __future__ import annotations

import argparse
import importlib.util as imputil
import json
import zipfile
from pathlib import Path

from PyQt6.QtCore import QByteArray, QDataStream, QIODevice, qChecksum


# CHECKSUM LIGHT.TASTE: 54659
class PropertyAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        print(parser, namespace, values, option_string)
        return super().__call__(parser, namespace, values, option_string)


def convert_to_bin(destination: Path, res_file: Path) -> int:
    if res_file.exists() and destination.suffix == ".bin":
        if res_file.suffix == ".py":
            spec = imputil.spec_from_file_location("resources", res_file.as_posix())
            module = imputil.module_from_spec(spec)
            spec.loader.exec_module(module)

            qt_resource_data: bytes = getattr(module, "qt_resource_data", b"")
            qt_resource_name: bytes = getattr(module, "qt_resource_name", b"")
            qt_resource_struct: bytes = getattr(module, "qt_resource_struct", b"")

        elif res_file.suffix in (".rcc", ".qrc"):
            print("Direct conversion of rcc or qrc files not supported yet")
            return 0

        else:
            print(f"Wrong resource file type: {res_file.suffix}. Must be '.py'")

        if all((qt_resource_data, qt_resource_name, qt_resource_struct)):
            bytearr = QByteArray()
            stream = QDataStream(bytearr, QIODevice.OpenModeFlag.WriteOnly)
            stream.writeBytes(b"tcha-qrc")
            stream.writeBytes(qt_resource_data)
            stream.writeBytes(qt_resource_name)
            stream.writeBytes(qt_resource_struct)

            chksum = qChecksum(bytearr)

            with open(destination, "wb") as f:
                f.write(bytearr.data())

            return chksum
        else:
            print(
                "Could not find one or either attributes: 'qt_resource_data', 'qt_resource_name', 'qt_resource_struct'"
            )

    return 0


def pack_theme(
    destination: Path, properties: Path, bin: Path, stylesheet: Path
) -> bool:
    """Packs the files under the given paths into a .taste-file at 'destination'. Returns True if the operation was successful"""
    try:
        if (
            destination.suffix == ".taste"
            and properties.suffix == ".json"
            and bin.suffix == ".bin"
            and stylesheet.suffix == ".qss"
        ):
            with open(properties.as_posix(), "r", encoding="utf-8") as json_f:
                json_properties = json.load(json_f)
            file = zipfile.ZipFile(destination.as_posix(), mode="w")
            file.write(properties.as_posix(), "properties.json")
            file.write(bin.as_posix(), json_properties["resources"])
            file.write(stylesheet.as_posix(), json_properties["stylesheet"])
            file.close()
            return True

        print(
            "Either one or more files have the wrong type: \ndestination : taste\nproperties : json\nresources : bin\nstylesheet : qss "
        )
        return False

    except KeyError as e:
        print(f"properties.json: File name for '{e.args}' could not be found.")
        return False
    except FileNotFoundError as e:
        print(f"File '{e.filename}' could not be found.")
        return False


def get_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="TPACK",
        description="Pack and organise taste-files for Techart",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    parser_pack = subparsers.add_parser("pack", help="Pack a taste-file ")
    parser_pack.add_argument(
        "paths",
        nargs=4,
        metavar="Paths",
        help="Arguments: [DESTINATION_PATH], [PROPERTIES_PATH],\n [RESOURCES_PATH] and [STYLESHEET_PATH]",
    )
    parser_pack.set_defaults(func=handle_pack)

    parser_bin = subparsers.add_parser(
        "bin", help="Convert resource python file generated by rcc into binary file"
    )
    parser_bin.add_argument(
        "paths",
        nargs=2,
        metavar="Paths",
        help="Arguments: [DESTINATION_PATH] [PY_FILE]",
    )
    parser_bin.set_defaults(func=handle_bin)

    parser_taste = subparsers.add_parser("taste", help="Edit taste-file")
    parser_taste.add_argument(
        "--properties",
        "-p",
        nargs="+",
        metavar="[KEY] [VALUE]",
        action=PropertyAction,
        help="Specify a KEY to show the current value and optionally a VALUE to be changed in the theme's properties file",
    )

    # action = parser.add_argument(
    #     "--taste",
    #     "-t",
    #     type=str,
    #     nargs=2,
    #     help="Access and modify taste-file",
    # )
    return parser


def handle_bin(namespace: argparse.Namespace) -> None:
    destination, resources = map(lambda path: Path(path), namespace.paths)
    result = convert_to_bin(destination, resources)
    if result:
        print(f"Successfully converted to binary file. Checksum: {result}")
    else:
        print("Failed to convert")


def handle_pack(namespace: argparse.Namespace):
    destination, properties, resources, stylesheet = map(
        lambda path: Path(path), namespace.paths
    )
    print(f"Files: {destination}", properties, resources, stylesheet, sep=", ")
    result = pack_theme(
        destination.name, properties.name, resources.name, stylesheet.name
    )
    if result:
        print("Successfully composed taste-file")
    else:
        print("Failed to compose taste-file")


def main():
    parser = get_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
